/**
* @author Niklas Lundkvist, Deloitte
* @date 2020
*
* @description TODO
*/

public class IRR_MOD_FlowVariables {

    @InvocableVariable
    public IRR_MOD_CancelInfo cancelInfo;

    @InvocableVariable
    public IRR_MOD_DelayInfo delayInfo;

    @InvocableVariable
    public IRR_MOD_NewInfo newInfo;

    @InvocableVariable
    public IRR_MOD_PassengerInfo passengerInfo;

    @InvocableVariable
    public IRR_MOD_RebookInfo rebookInfo;

    @InvocableVariable
    public IRR_MOD_CustomInfo customInfo;
}