import { createElement } from 'lwc';
import C_Json2CsvUtils from 'c/c_Json2CsvUtils';

describe('c-c-json2-csv-utils', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-c-json2-csv-utils', {
            is: C_Json2CsvUtils
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});